// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmsfTlyhkD13EEpDARrYq6mgnRzbUnR0s',
    appId: '1:470720197541:web:b19bf0c2f0f90bab996e4c',
    messagingSenderId: '470720197541',
    projectId: 'thunder-wallet',
    authDomain: 'thunder-wallet.firebaseapp.com',
    storageBucket: 'thunder-wallet.appspot.com',
    measurementId: 'G-G7BLSXWMG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKCyVmnBGfM_fFTIMqw30BO-cgl1TU5PE',
    appId: '1:470720197541:android:10cbc398ab3c8139996e4c',
    messagingSenderId: '470720197541',
    projectId: 'thunder-wallet',
    storageBucket: 'thunder-wallet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz3sYIgCtMy1J4iBypoRyBI-dasS4pUHs',
    appId: '1:470720197541:ios:559ee0993d89aad3996e4c',
    messagingSenderId: '470720197541',
    projectId: 'thunder-wallet',
    storageBucket: 'thunder-wallet.appspot.com',
    iosBundleId: 'com.thunder.wallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz3sYIgCtMy1J4iBypoRyBI-dasS4pUHs',
    appId: '1:470720197541:ios:559ee0993d89aad3996e4c',
    messagingSenderId: '470720197541',
    projectId: 'thunder-wallet',
    storageBucket: 'thunder-wallet.appspot.com',
    iosBundleId: 'com.thunder.wallet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmsfTlyhkD13EEpDARrYq6mgnRzbUnR0s',
    appId: '1:470720197541:web:9e293c9a646698cf996e4c',
    messagingSenderId: '470720197541',
    projectId: 'thunder-wallet',
    authDomain: 'thunder-wallet.firebaseapp.com',
    storageBucket: 'thunder-wallet.appspot.com',
    measurementId: 'G-G2527S166V',
  );
}
